dbt_sales:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: mysecretpassword
      port: 5432
      dbname: sales
      schema: modeling
      threads: 4
      keepalives_idle: 0
      sslmode: prefer
