version: 2

models:
  - name: stg_sales
    description: "Sales data with quarter information"
    columns:
      - name: sale_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: product_id
        description: "The ID of the product"
        data_tests:
          - not_null
      - name: retailer_id
        description: "The ID of the retailer"
        data_tests:
          - not_null
      - name: quantity
        description: "The quantity sold"
        data_tests:
          - not_null
      - name: price
        description: "The price of the product"
        data_tests:
          - not_null
      - name: sale_date
        description: "The date of the sale"
        data_tests:
          - not null